version: '3.4'

services:
  mocksso:
    image: ukti/mock-sso
    environment:
      - MOCK_SSO_PORT=7070
      - MOCK_SSO_USERNAME=ravi.kotecha@digital.trade.gov.uk
      - MOCK_SSO_EMAIL_USER_ID=ravi.kotecha@digital.trade.gov.uk
      - MOCK_SSO_SCOPE="read,write,profile"
      - MOCK_SSO_TOKEN=token
      - MOCK_SSO_VALIDATE_TOKEN=False
    expose:
      - 7070
    ports:
      - 7070:7070
    networks:
      - lite

  db:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lite-api
    expose:
      - 5432
    ports:
      - 5462:5432
    networks:
      - lite

  api:
    env_file:
      - .env
    build: .
    volumes:
      - .:/app
    ports:
      - 8100:8100
    links:
      - db
    expose:
      - 8100
    command: ./manage.py runserver 0.0.0.0:${PORT:-8100}
    networks:
      - lite
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms128m -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - lite

  redis:
    image: "redis:5-alpine"
    container_name: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - lite

networks:
  lite:
    external: true
volumes:
  elasticsearch-data:
    driver: local
